google_analytics: UA-NNNNNNNN-N

# theme: jekyll-theme-console

header_pages:
  - index.md
  - about.md
  # - posts.md
  - contact.md

footer: 'follow me on <a href="https://github.com/kbsooo">github</a>'

style: dark
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

baseurl: ""
