baseURL = "https://kbsooo.github.io/"
languageCode = "en-us"
title = "kbsoo" # the title of your site

theme = "dario-main"

[params]
  author = "kbsoo!" # the author of the site
  description = "blog" # a description of your site that will be used in the meta tags

  customCSS = ["/static/css/custom.css"]

  [params.homeInfoParams]
    Title = "Hello!" # the text to display on the "/" homepage
    Content = "I am a third-year student majoring in Computer Engineering at Myongji University. My primary instersts lie in machine learning, data analysis, and artificial intelligence. I always enjoy learning and am eager to find opportunities where I can continue to grow and expand my skills in these areas. I feel truly grateful and excited to be born in an era where new technologies emrge so frequently. My dream is to develop a product that people will widely recognize and associate with my name, Kang Byungsoo"
    Description = "A minimal web log." # The description of the home page that will be used in the open graph meta tags