baseURL = 'https://kbsooo.github.io/'
defaultContentLanguage = 'en'
title = 'KBSOO'
theme = 'papermod'

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
  [languages.ko]
    languageCode = 'ko-KR'
    languageName = '한국어'
    weight = 2

[pagination]
  pagerSize = 5

# 추가할 수 있는 설정들
[params]
  description = "사이트 설명"
  author = "작성자명"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  hideAuthor = true

[params.homeInfoParams]
  Title = "Byungsoo Kang"
  Content = "Computer Science Student | Interested in deep neural networks"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/kbsooo"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/byungsoo-kang-511b82342/"

[[params.socialIcons]]
  name = "culture"
  url = "https://kbsooo.github.io/culture/"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"